// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rdf_to_rwtbl_cpp
List rdf_to_rwtbl_cpp(std::vector<std::string> rdf, std::vector<std::string> keep_cols, String const scenario, bool add_ym, bool big, size_t row_index, int trace_start);
RcppExport SEXP _RWDataPlyr_rdf_to_rwtbl_cpp(SEXP rdfSEXP, SEXP keep_colsSEXP, SEXP scenarioSEXP, SEXP add_ymSEXP, SEXP bigSEXP, SEXP row_indexSEXP, SEXP trace_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type rdf(rdfSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type keep_cols(keep_colsSEXP);
    Rcpp::traits::input_parameter< String const >::type scenario(scenarioSEXP);
    Rcpp::traits::input_parameter< bool >::type add_ym(add_ymSEXP);
    Rcpp::traits::input_parameter< bool >::type big(bigSEXP);
    Rcpp::traits::input_parameter< size_t >::type row_index(row_indexSEXP);
    Rcpp::traits::input_parameter< int >::type trace_start(trace_startSEXP);
    rcpp_result_gen = Rcpp::wrap(rdf_to_rwtbl_cpp(rdf, keep_cols, scenario, add_ym, big, row_index, trace_start));
    return rcpp_result_gen;
END_RCPP
}
