#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/*
 * Generated by runnning:
 * tools::package_native_routine_registration_skeleton(".")
*/

/* FIXME: 
  Check these declarations against the C/Fortran source code.
*/
  
/* .Call calls */
extern SEXP _RWDataPlyr_rdf_to_rwtbl_cpp(SEXP, SEXP, SEXP, SEXP);
extern SEXP _RWDataPlyr_rdf_to_rwtbl_cpp_old(SEXP);

static const R_CallMethodDef CallEntries[] = {
  {"_RWDataPlyr_rdf_to_rwtbl_cpp",     (DL_FUNC) &_RWDataPlyr_rdf_to_rwtbl_cpp,     4},
  {"_RWDataPlyr_rdf_to_rwtbl_cpp_old", (DL_FUNC) &_RWDataPlyr_rdf_to_rwtbl_cpp_old, 1},
  {NULL, NULL, 0}
};

void R_init_RWDataPlyr(DllInfo *dll)
{
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
