# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdf_to_rwtbl_cpp <- function(rdf) {
    .Call('_RWDataPlyr_rdf_to_rwtbl_cpp', PACKAGE = 'RWDataPlyr', rdf)
}

rdf_to_rwtbl_cpp_old <- function(rdf) {
    .Call('_RWDataPlyr_rdf_to_rwtbl_cpp_old', PACKAGE = 'RWDataPlyr', rdf)
}

