# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdf_to_rwtbl_cpp <- function(rdf, keep_cols, scenario = NA_character_, add_ym = TRUE, big = FALSE, row_index = 0L, last_trace = 0L) {
    .Call(`_RWDataPlyr_rdf_to_rwtbl_cpp`, rdf, keep_cols, scenario, add_ym, big, row_index, last_trace)
}

