
#' optional column names included in csv files created by RiverWare
#' 
#' leaving this for now, as we may want to determine scenario dimensions by 
#' figuring out which columns are not the optional columns autogenerated
#' 
#' @noRd
rwCsvOptionalCols <- function() {
  c("Object Name", "Object Type", "Slot Name", "Slot Name with Unit", "Unit", 
    "Timestep Size", "Year", "Month", "Model Name", "Ruleset File Name", 
    "Input DMI Name", "MRM Config Name", "MRM Descriptors")
}

#' Read in RiverWare Data
#' 
#' Read in a CSV file created from RiverWare. If the CSV file does not contain 
#' column names that RiverWare always uses (see Details), then it assumes that the CSV file
#' was not created from RiverWare and throws an error. It also removes spaces
#' from the column names, and adjusts the \code{Object.Slot} and \code{Slot Value}
#' columns to be \code{ObjectSlot} and \code{Value}, respectively.
#' 
#' The required column names are: \code{Run Number}, \code{Trace Number}, 
#' \code{Object.Slot}, \code{Timestep}, \code{Slot Value}. See the CSV output 
#' section of the 
#' \href{http://www.riverware.org/PDF/RiverWare/documentation/MRM.pdf}{RiverWare documentation}
#' for more information on the other optional column names.
#' 
#' This function uses \code{data.table::\link[data.table]{fread}()} to read in 
#' the CSV file, and forces it to expect a CSV file, expect headers, and return
#' a \code{data.frame}.
#' 
#' @param file The name of the file which the data are to be read from. Either an
#' absolute or relative path.
#' 
#' @return A data frame (\code{\link[base]{data.frame}}) containing a 
#' representation of the data in the file.
#' 
#' @examples 
#' zz <- readRwCsv(system.file(
#'   "extdata/Scenario/ISM1988_2014,2007Dems,IG,Most",
#'   "KeySlots.csv",
#'   package = "RWDataPlyr"
#' ))
#' 
#' @seealso \code{\link{read.rdf}}
#' 
#' @export

readRwCsv <- function(file) {
  # read in the file
  zz <- data.table::fread(file, sep = ',', header = TRUE, data.table = FALSE)
  
  # check column names
  reqColumns <- c("Run Number", "Trace Number", "Object.Slot", "Timestep", "Slot Value")
  
  if(!all(reqColumns %in% colnames(zz)))
    stop("The ", file, 
         " csv does not have all required column names.\n",
         "It is unlikely this is a csv file from RiverWare.\n",
         "Required column names are: ", paste(reqColumns, collapse = ", "))
  
  
  # update column names so they contain no spaces
  colnames(zz) <- gsub(" ", "", colnames(zz), fixed = TRUE)
  # remove . from Object.Slot
  i <- which(colnames(zz) == "Object.Slot")
  colnames(zz)[i] <- "ObjectSlot"
  # change slot value to just Value
  i <- which(colnames(zz) == "SlotValue")
  colnames(zz)[i] <- "Value"
  
  zz
}